version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=mysql_native_password
      - --ssl=0   # disable SSL globally
      - --log-bin-trust-function-creators=1  # FIX for Zabbix triggers/functions
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zbxnet

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ZBX_CACHE_SIZE: ${ZBX_CACHE_SIZE}
      ZBX_SERVER_NAME: ${ZBX_SERVER_NAME}
      ZBX_HOSTNAME: ${ZBX_HOSTNAME}
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    volumes:
      - ./zabbix-server:/var/lib/zabbix
    networks:
      - zbxnet

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-latest
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    depends_on:
      - mysql
      - zabbix-server
    ports:
      - "80:8080"
    networks:
      - zbxnet
  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zabbix-agent
    environment:
      - ZBX_SERVER=zabbix-zabbix-server-1
      - ZBX_SERVER_ACTIVE=zabbix-zabbix-server-1
      - ZBX_HOSTNAME=ec2-monitor
    volumes:
      - /opt/zabbix/zabbix-agent/conf/zabbix_agent2.conf:/etc/zabbix/zabbix_agent2.conf:ro
      - /opt/zabbix/logs:/var/log/zabbix
    depends_on:
      - zabbix-server
    networks:
      - zbxnet


volumes:
  mysql_data:

networks:
  zbxnet:

